# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

#ALEX

pod 'FrameAccessor'
pod 'Timepiece'
pod 'ChameleonFramework'
pod 'SVProgressHUD'
pod 'MGSwipeTableCell'
pod 'pop'
pod 'OAuthSwift'
pod 'TextFieldEffects'
pod 'RealmSwift'

#VADIM

pod 'Alamofire', :inhibit_warnings => true
pod 'SwiftyJSON'