# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!
inhibit_all_warnings!

#ALEX

pod 'FrameAccessor'
pod 'Timepiece'
pod 'ChameleonFramework'
pod 'SVProgressHUD'
pod 'MGSwipeTableCell'
pod 'pop'
pod 'OAuthSwift'
pod 'TextFieldEffects'
pod 'RealmSwift'
pod 'Spring', :git => 'https://github.com/MengTo/Spring.git', :branch => 'swift2'

#VADIM

pod 'Alamofire', :inhibit_warnings => true
pod 'SwiftyJSON'